const mongoose = require('../db/connection');
const Schema = mongoose.Schema;

const ThisWeeksGames = new Schema ({
    week: Number,
    results: [],
    gameOneFavorite: String,
    gameOneUnderdog: String,
    gameOneSpread: Number,
    gameTwoFavorite: String,
    gameTwoUnderdog: String,
    gameTwoSpread: Number,
    gameThreeFavorite: String,
    gameThreeUnderdog: String,
    gameThreeSpread: Number,
    gameFourFavorite: String,
    gameFourUnderdog: String,
    gameFourSpread: Number,
    gameFiveFavorite: String,
    gameFiveUnderdog: String,
    gameFiveSpread: Number,
    gameSixFavorite: String,
    gameSixUnderdog: String,
    gameSixSpread: Number,
    gameSevenFavorite: String,
    gameSevenUnderdog: String,
    gameSevenSpread: Number,
    gameEightFavorite: String,
    gameEightUnderdog: String,
    gameEightSpread: Number,
    gameNineFavorite: String,
    gameNineUnderdog: String,
    gameNineSpread: Number,
    gameTenFavorite: String,
    gameTenUnderdog: String,
    gameTenSpread: Number,
    gameElevenFavorite: String,
    gameElevenUnderdog: String,
    gameElevenSpread: Number,
    gameTwelveFavorite: String,
    gameTwelveUnderdog: String,
    gameTwelveSpread: Number,
    gameThirteenFavorite: String,
    gameThirteenUnderdog: String,
    gameThirteenSpread: Number,
    gameFourteenFavorite: String,
    gameFourteenUnderdog: String,
    gameFourteenSpread: Number,
    gameFifteenFavorite: String,
    gameFifteenUnderdog: String,
    gameFifteenSpread: Number,
    mondayNightPoints: Number
})

module.exports = mongoose.model('ThisWeeksGames', ThisWeeksGames);