const mongoose = require('../db/connection');
const Schema = mongoose.Schema;

const ThisWeeksGames = new Schema ({
    week: Int,
    results: [],
    gameOneFavorite: String,
    gameOneUnderdog: String,
    gameOneSpread: Int,
    gameTwoFavorite: String,
    gameTwoUnderdog: String,
    gameTwoSpread: Int,
    gameThreeFavorite: String,
    gameThreeUnderdog: String,
    gameThreeSpread: Int,
    gameFourFavorite: String,
    gameFourUnderdog: String,
    gameFourSpread: Int,
    gameFiveFavorite: String,
    gameFiveUnderdog: String,
    gameFiveSpread: Int,
    gameSixFavorite: String,
    gameSixUnderdog: String,
    gameSixSpread: Int,
    gameSevenFavorite: String,
    gameSevenUnderdog: String,
    gameSevenSpread: Int,
    gameEightFavorite: String,
    gameEightUnderdog: String,
    gameEightSpread: Int,
    gameNineFavorite: String,
    gameNineUnderdog: String,
    gameNineSpread: Int,
    gameTenFavorite: String,
    gameTenUnderdog: String,
    gameTenSpread: Int,
    gameElevenFavorite: String,
    gameElevenUnderdog: String,
    gameElevenSpread: Int,
    gameTwelveFavorite: String,
    gameTwelveUnderdog: String,
    gameTwelveSpread: Int,
    gameThirteenFavorite: String,
    gameThirteenUnderdog: String,
    gameThirteenSpread: Int,
    gameFourteenFavorite: String,
    gameFourteenUnderdog: String,
    gameFourteenSpread: Int,
    gameFifteenFavorite: String,
    gameFifteenUnderdog: String,
    gameFifteenSpread: Int,
    mondayNightPoints: Int
})

module.exports = mongoose.model('ThisWeeksGames', ThisWeeksGames);